steps:

  - label: ':android: Coding standards checks'
    timeout_in_minutes: 20
    agents:
      queue: macos-12-arm
    command: './gradlew --continue license detekt lint ktlintCheck'

  - label: ':android: JVM tests'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: './gradlew test'

  - label: ':android: Lint test scenarios'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - cd features/fixtures/mazeracer
      - ./gradlew ktlintCheck detekt

  - label: ':android: Android size reporting'
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    command: scripts/run-sizer.sh


  - label: ':bitbar: ANDROID_9 tests'
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        upload:
          - "./maze_output/failed/**/*"
          - "./maze_output/passed/**/*"
      docker-compose#v4.8.0:
        pull: android-maze-runner
        run: android-maze-runner
        service-ports: true
        command:
          - "--app=189198096"
          - "--farm=bb"
          - "--device=ANDROID_9"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: {{matrix}} tests'
    timeout_in_minutes: 60
    matrix:
      - "ANDROID_13"
    plugins:
      artifacts#v1.9.0:
        upload:
          - "./maze_output/failed/**/*"
          - "./maze_output/passed/**/*"
      docker-compose#v4.8.0:
        pull: android-maze-runner
        run: android-maze-runner
        service-ports: true
        command:
          - "--app=189198096"
          - "--farm=bb"
          - "--device={{matrix}}"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager
