FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/android:performance-release as android

WORKDIR /app

# Copy gradle files
COPY gradlew gradle.properties /app/
COPY gradle/ /app/gradle/
COPY build.gradle.kts settings.gradle.kts /app/

# Copy sdk source files
COPY bugsnag-android-performance/ bugsnag-android-performance/
COPY bugsnag-android-performance-api/ bugsnag-android-performance-api/
COPY bugsnag-android-performance-impl/ bugsnag-android-performance-impl/
COPY bugsnag-plugin-android-performance-appcompat/ bugsnag-plugin-android-performance-appcompat/
COPY bugsnag-plugin-android-performance-compose/ bugsnag-plugin-android-performance-compose/
COPY bugsnag-plugin-android-performance-coroutines/ bugsnag-plugin-android-performance-coroutines/
COPY bugsnag-plugin-android-performance-named-spans/ bugsnag-plugin-android-performance-named-spans/
COPY bugsnag-plugin-android-performance-okhttp/ bugsnag-plugin-android-performance-okhttp/
COPY scripts/ scripts/
COPY LICENSE LICENSE

CMD "scripts/docker-publish.sh"
