FROM ubuntu:24.04@sha256:99c35190e22d294cdace2783ac55effc69d32896daaa265f0bbedbcde4fbe3e5

RUN apt-get update > /dev/null
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget maven gnupg1 cppcheck libncurses6 jq clang-format unzip curl git
RUN apt-get clean > /dev/null

ENV ANDROID_SDK_ROOT="/sdk"
ENV ANDROID_CMDLINE_TOOLS="${ANDROID_SDK_ROOT}/cmdline-tools/latest"
ENV PATH="${PATH}:${ANDROID_CMDLINE_TOOLS}/bin"
ENV CMDLINE_TOOLS_NAME="commandlinetools-linux-6858069_latest.zip"
WORKDIR $ANDROID_SDK_ROOT

RUN mkdir ~/.gradle

# Download Android command line tools
RUN wget https://dl.google.com/android/repository/${CMDLINE_TOOLS_NAME} -q
RUN mkdir cmdline-tools
RUN unzip -q ${CMDLINE_TOOLS_NAME} -d /sdk/cmdline-tools
RUN mv /sdk/cmdline-tools/cmdline-tools $ANDROID_CMDLINE_TOOLS
RUN rm $CMDLINE_TOOLS_NAME

# Install Android tools using sdkmanager
RUN yes | sdkmanager "platform-tools" > /dev/null
RUN yes | sdkmanager "platforms;android-34" > /dev/null

# Install bundletool
RUN wget -q https://github.com/google/bundletool/releases/download/1.4.0/bundletool-all-1.4.0.jar
RUN mv bundletool-all-1.4.0.jar bundletool.jar
